language: python
sudo: required
dist: xenial
python:
#  - "2.6"
#  - "2.7"
#  - "3.3"
#  - "3.4"
  - "3.5"
  - "3.5-dev"  # 3.5 development branch
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7"
# command to install dependencies
before_install:
  - sudo apt update
  # Install tesseract
  - sudo apt install tesseract-ocr libtesseract-dev
  # Install geckodriver
  - sudo apt install wget make
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
  - sudo sh -c 'tar -xvzf geckodriver* -O > /usr/local/bin/geckodriver'
  - sudo chmod +x /usr/local/bin/geckodriver
  - export PATH=$PATH:/usr/local/bin/geckodriver
  # Install firefox
  - sudo apt install firefox
  # Install scrot
  - sudo apt install scrot
  # Install pre-trained models
  - wget https://github.com/OlafenwaMoses/ImageAI/releases/download/1.0/yolo.h5
install:
  # Install python packages
  - pip install -r requirements.txt
  - pip install mypy
  - pip install pytest
  - pip install pytest-black
  - pip install pytest-cov
  - pip install python-coveralls
before_script:
- export DISPLAY=:0
script:
  - mypy . --ignore-missing-imports
  - xvfb-run --server-args="-screen 0, 1280x768x24" -a pytest -vs --black --cov-report term-missing --cov=decaptcha/
after_script:
  - coveralls
